### ISSUE TITLE
What is that?

### ISSUE THREAD

**Issue by miratcan** [gnyaliyeva/aliyevahukuk#3]
https://github.com/gnyaliyeva/aliyevahukuk/blob/5efc9d562e2d7da4f6f3360faad02173500c3941/src/components/layout.js#L18

**Comment by gnyaliyeva** [comment]
her return tek bir block dondurmek zorunda. boyle yapinca icindeki elemenleri yani blocklari tek bir blockmus gibi gosteriyor ve donduruyor.
